repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      #      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  - repo: local
    hooks:
      - id: app-prettier
        name: run prettier
        language: system
        files: ^.*$
        types_or: [javascript, json]
        entry: |
          bash -c 'bun run fix:prettier "${@}"' --
