# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%-d %B %Y") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% set_global order = ["🚀 Features", "🐛 Bug Fixes", "⚡ Performance", "🚜 Refactor", "📚 Documentation", "🎨 Styling", "🧪 Testing", "🏗️ Build System", "👷 CI/CD", "⚙️ Miscellaneous Tasks", "🛡️ Security", "◀️ Revert", "💼 Other"] %}\
{% for group_name in order %}\
    {% set group_commits = commits | filter(attribute="group", value=group_name) %}\
    {% if group_commits | length > 0 %}\
    ### {{ group_name | striptags | trim | upper_first }}
    {% for commit in group_commits %}
        - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{% if commit.breaking %}[**BREAKING**] {% endif %}{{ commit.message | upper_first }}
    {% endfor -%}
    {% endif %}\
{% endfor -%}

---

"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true
render_always = true
postprocessors = [
    { pattern = '\$REPO', replace = "https://github.com/ErenayDev/checkpoint-ts" },
]

[git]
conventional_commits = true
filter_unconventional = false
require_conventional = false
split_commits = false
commit_preprocessors = [
    { pattern = '^Bump (.+) from (.+) to (.+)\n[\s\S]*$', replace = "chore(deps): bump ${1} from ${2} to ${3}" },
    { pattern = '^Add benchmarks.*\n[\s\S]*$', replace = "feat: add benchmarks" },
    { pattern = '^Remove Dependabot.*\n[\s\S]*$', replace = "chore: remove dependabot" },
    { pattern = '^Add issue templates.*\n[\s\S]*$', replace = "docs: add issue templates" },
    { pattern = '^Add Contributor Covenant.*\n[\s\S]*$', replace = "docs: add code of conduct" },
    { pattern = '^Update issue templates.*\n[\s\S]*$', replace = "docs: update issue templates" },
    { pattern = '^Update README.*\n[\s\S]*$', replace = "docs: update readme" },
    { pattern = '^Merge .*\n[\s\S]*$', replace = "chore: merge branches" },
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}]($REPO/issues/${2}))" },
    { pattern = '\$REPO', replace = "https://github.com/ErenayDev/checkpoint-ts" },
]
protect_breaking_commits = true
commit_parsers = [
    { message = "^feat", group = "🚀 Features" },
    { message = "^fix", group = "🐛 Bug Fixes" },
    { message = "^perf", group = "⚡ Performance" },
    { message = "^refactor", group = "🚜 Refactor" },
    { message = "^doc", group = "📚 Documentation" },
    { message = "^style", group = "🎨 Styling" },
    { message = "^test", group = "🧪 Testing" },
    { message = "^build", group = "🏗️ Build System" },
    { message = "^ci", group = "👷 CI/CD" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore: merge", skip = true },
    { message = "^chore", group = "⚙️ Miscellaneous Tasks" },
    { body = ".*security", group = "🛡️ Security" },
    { message = "^revert", group = "◀️ Revert" },
    { message = ".*", group = "💼 Other" },
]
filter_commits = false
link_parsers = [
    { pattern = "#(\\d+)", href = "$REPO/issues/${1}" },
]
tag_pattern = "v[0-9].*"
skip_tags = "v0.1.0-beta.1"
sort_commits = "oldest"
